- name : variables
  hosts: local
  connection: local
  become: yes
  vars:
    NAME : "Anil Kumar"
    AGE : 25
  tasks:
  - name: print variables
    ansible.builtin.debug:
      msg : "Name is {{NAME}}, age is {{AGE}}"
