- name : variables
  hosts: local
  connection: local
  become: yes
  vars_files:
  - vars_input.yml
  tasks:
  - name: print variables
    ansible.builtin.debug:
      msg : "Name is {{NAME}}, age is {{AGE}}"