- name : variables
  hosts: local
  connection: local
  become: yes
  vars_prompt:
  - name: NAME
    prompt: Enter Name
    private: false
  - name: AGE
    prompt: Enter age
    private: false
  tasks:
  - name: print variables
    vars:
      NAME: "SUNIL"
      AGE: 30 
    ansible.builtin.debug:
      msg : "Name is {{NAME}}, age is {{AGE}}"