- name: testing loops
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: installing multiple pacakages
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    
    loop:
    - {name:"msyql", state:"present"}
    - {name:"msyql", state:"absent"}
    - {name:"nginx", state:"present"}