- name: testing when condition
  hosts: local
  connection: local
  become: yes
  vars:
    NAME: "ANIL KUMAR"
    AGE: "28"
  tasks:
  - name: when condition
    ansible.builtin.debug:
      msg: "NAME is {{ NAME }} and AGE is {{ AGE }}"
    when: AGE == 25
    